if(!sessionStorage.getItem("mc_admin"))location.href="index.html";
document.querySelector("#logout")?.addEventListener("click",e=>{e.preventDefault();sessionStorage.removeItem("mc_admin");location.href="index.html"});
const db=getDB();
function renderDashboard(){const stats=document.querySelector("#stats");if(!stats)return;const revenue=db.sales.reduce((s,x)=>s+x.total,0),low=db.products.filter(p=>p.stock<=p.minStock&&p.stock>0).length,out=db.products.filter(p=>p.stock<=0).length;stats.innerHTML=`<div class="stat"><small>Faturamento</small><strong>${money(revenue)}</strong></div><div class="stat"><small>Vendas</small><strong>${db.sales.length}</strong></div><div class="stat"><small>Produtos</small><strong>${db.products.length}</strong></div><div class="stat"><small>Estoque baixo</small><strong>${low+out}</strong></div>`;const days=[...Array(7)].map((_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(6-i));const key=d.toISOString().slice(0,10);return {key,label:d.toLocaleDateString("pt-BR",{weekday:"short"}),value:db.sales.filter(s=>s.date.slice(0,10)===key).reduce((a,s)=>a+s.total,0)}});const max=Math.max(...days.map(x=>x.value),1);document.querySelector("#chart").innerHTML=days.map(x=>`<div class="bar" style="height:${Math.max(5,x.value/max*85)}%"><span>${x.label}</span></div>`).join("");document.querySelector("#lowStock").innerHTML=`<table class="data-table"><thead><tr><th>Produto</th><th>Estoque</th><th>Status</th></tr></thead><tbody>${db.products.filter(p=>p.stock<=p.minStock).map(p=>`<tr><td>${p.name}</td><td>${p.stock}</td><td>${p.stock<=0?"Esgotado":"Estoque baixo"}</td></tr>`).join("")||"<tr><td colspan=3>Nenhum alerta.</td></tr>"}</tbody></table>`}
function renderProducts(){const el=document.querySelector("#productsTable");if(!el)return;el.innerHTML=db.products.map(p=>`<tr><td><b>${p.name}</b></td><td>${p.category}</td><td>${money(p.promo||p.price)}</td><td>${p.stock}</td><td>${p.active===false?"Inativo":"Ativo"}</td><td><a class="admin-btn primary" href="produto-form.html?id=${p.id}">Editar</a> <button class="admin-btn red" onclick="deleteProduct('${p.id}')">Excluir</button></td></tr>`).join("")}
function deleteProduct(id){if(!confirm("Excluir este produto?"))return;const d=getDB();d.products=d.products.filter(p=>p.id!==id);saveDB(d);location.reload()}
function renderStock(){const el=document.querySelector("#stockTable");if(!el)return;el.innerHTML=db.products.map(p=>`<tr><td>${p.name}</td><td>${p.id}</td><td>${p.stock}</td><td>${p.minStock}</td><td>${p.stock<=0?"🔴 Esgotado":p.stock<=p.minStock?"🟡 Baixo":"🟢 Normal"}</td><td><a class="admin-btn primary" href="produto-form.html?id=${p.id}">Ajustar</a></td></tr>`).join("")}
function renderSales(){const sp=document.querySelector("#saleProduct");if(!sp)return;sp.innerHTML=db.products.map(p=>`<option value="${p.id}">${p.name} — estoque ${p.stock}</option>`).join("");document.querySelector("#saleForm").addEventListener("submit",e=>{e.preventDefault();const d=getDB(),p=d.products.find(x=>x.id===sp.value),qty=Number(document.querySelector("#saleQty").value);if(!p||qty<1||qty>p.stock){alert("Quantidade maior que o estoque disponível.");return}const price=p.promo||p.price;p.stock-=qty;d.sales.unshift({id:uid("sale"),productId:p.id,product:p.name,qty,total:price*qty,customer:document.querySelector("#saleCustomer").value||"Não informado",payment:document.querySelector("#salePayment").value,date:new Date().toISOString()});saveDB(d);toast("Venda registrada e estoque atualizado.");setTimeout(()=>location.reload(),700)});const table=document.querySelector("#salesTable");table.innerHTML=db.sales.map(s=>`<tr><td>${new Date(s.date).toLocaleString("pt-BR")}</td><td>${s.product}</td><td>${s.customer}</td><td>${s.payment}</td><td>${s.qty}</td><td>${money(s.total)}</td></tr>`).join("")||"<tr><td colspan=6>Nenhuma venda registrada.</td></tr>"}
function renderFinance(){const el=document.querySelector("#financeStats");if(!el)return;const total=db.sales.reduce((a,s)=>a+s.total,0),qty=db.sales.reduce((a,s)=>a+s.qty,0);el.innerHTML=`<div class="stat"><small>Faturamento bruto</small><strong>${money(total)}</strong></div><div class="stat"><small>Quantidade vendida</small><strong>${qty}</strong></div><div class="stat"><small>Ticket médio</small><strong>${money(db.sales.length?total/db.sales.length:0)}</strong></div><div class="stat"><small>Produto mais vendido</small><strong style="font-size:16px">${topProduct()}</strong></div>`;const months={};db.sales.forEach(s=>{const k=s.date.slice(0,7);months[k]??={q:0,v:0};months[k].q++;months[k].v+=s.total});document.querySelector("#monthTable").innerHTML=Object.entries(months).sort().reverse().map(([m,x])=>`<tr><td>${m}</td><td>${x.q}</td><td>${money(x.v)}</td></tr>`).join("")||"<tr><td colspan=3>Nenhuma venda registrada.</td></tr>"}
function topProduct(){const m={};db.sales.forEach(s=>m[s.product]=(m[s.product]||0)+s.qty);const x=Object.entries(m).sort((a,b)=>b[1]-a[1])[0];return x?x[0]:"—"}
function renderCustomers(){const el=document.querySelector("#customersTable");if(!el)return;const m={};db.sales.forEach(s=>{if(!m[s.customer])m[s.customer]={q:0,v:0,last:s.date};m[s.customer].q+=s.qty;m[s.customer].v+=s.total;if(s.date>m[s.customer].last)m[s.customer].last=s.date});el.innerHTML=Object.entries(m).map(([n,x])=>`<tr><td>${n}</td><td>${x.q}</td><td>${money(x.v)}</td><td>${new Date(x.last).toLocaleDateString("pt-BR")}</td></tr>`).join("")||"<tr><td colspan=4>Nenhum cliente registrado.</td></tr>"}
function renderSettings(){const f=document.querySelector("#settingsForm");if(!f)return;const s=getDB().settings;store.value=s.store;whatsapp.value=s.whatsapp;phone1.value=s.phone1;phone2.value=s.phone2;f.addEventListener("submit",e=>{e.preventDefault();const d=getDB();d.settings={store:store.value,whatsapp:whatsapp.value.replace(/\D/g,""),phone1:phone1.value,phone2:phone2.value};saveDB(d);toast("Configurações salvas.")})}
renderDashboard();renderProducts();renderStock();renderSales();renderFinance();renderCustomers();renderSettings();