document.addEventListener("DOMContentLoaded",()=>{
document.querySelector(".menu-toggle")?.addEventListener("click",()=>document.querySelector(".nav")?.classList.toggle("menu-open"));
document.querySelectorAll("[data-whatsapp]").forEach(a=>a.href=waLink());
const grid=document.querySelector("#productGrid");
if(grid){const search=document.querySelector("#searchInput"),cat=document.querySelector("#categoryFilter"),sort=document.querySelector("#sortFilter");
const render=()=>{let ps=getDB().products.filter(p=>p.active!==false);const q=(search.value||"").toLowerCase().trim();if(q)ps=ps.filter(p=>[p.name,p.category,p.measure,p.type,p.description].join(" ").toLowerCase().includes(q));if(cat.value)ps=ps.filter(p=>p.category===cat.value);if(sort.value==="priceAsc")ps.sort((a,b)=>(a.promo||a.price)-(b.promo||b.price));if(sort.value==="priceDesc")ps.sort((a,b)=>(b.promo||b.price)-(a.promo||a.price));if(sort.value==="name")ps.sort((a,b)=>a.name.localeCompare(b.name));if(sort.value==="featured")ps.sort((a,b)=>Number(b.featured)-Number(a.featured));grid.innerHTML=ps.map(card).join("");document.querySelector("#emptyState").classList.toggle("hidden",ps.length>0)}
const card=p=>{const price=p.promo>0?p.promo:p.price;return `<article class="product-card"><div class="product-img"><img src="${p.image||"assets/hero-cama.jpg"}" alt="${p.name}"><span class="badge ${p.offer?"offer":""}">${p.offer?"OFERTA":p.stock>0?"DISPONÍVEL":"ESGOTADO"}</span></div><div class="product-body"><span class="product-cat">${p.category} · ${p.measure||""}</span><h3 class="product-name">${p.name}</h3><p class="product-desc">${p.description||""}</p><div class="price">${p.promo>0?`<span class="old-price">${money(p.price)}</span>`:""}${money(price)}</div><div class="stock">${p.stock>0?`${p.stock} unidade(s) em estoque`:"Produto esgotado"}</div><div class="card-actions"><a class="btn btn-dark" href="produto.html?id=${encodeURIComponent(p.id)}">Ver produto</a><a class="btn btn-green" target="_blank" href="${waLink(`Olá! Tenho interesse no produto ${p.name}. Gostaria de saber preço e disponibilidade.`)}">WhatsApp</a></div></div></article>`};
[search,cat,sort].forEach(x=>x?.addEventListener("input",render));render();document.querySelectorAll(".category-card").forEach(b=>b.addEventListener("click",()=>{cat.value=b.dataset.category;document.querySelector("#produtos").scrollIntoView({behavior:"smooth"});render()}))}
const detail=document.querySelector("#productDetail");
if(detail){const id=new URLSearchParams(location.search).get("id"),p=getDB().products.find(x=>x.id===id);if(!p){detail.innerHTML="<div class='empty'>Produto não encontrado.</div>"}else{const price=p.promo>0?p.promo:p.price;detail.innerHTML=`<div class="product-detail"><div class="detail-gallery"><img src="${p.image||"assets/hero-cama.jpg"}" alt="${p.name}"></div><div class="detail-info"><span class="eyebrow dark">${p.category}</span><h1>${p.name}</h1><p class="desc">${p.description||""}</p><div class="detail-price">${p.promo>0?`<span class="old-price">${money(p.price)}</span>`:""}${money(price)}</div><div class="specs"><div class="spec"><small>Medida</small><b>${p.measure||"—"}</b></div><div class="spec"><small>Tipo</small><b>${p.type||"—"}</b></div><div class="spec"><small>Estoque</small><b>${p.stock>0?p.stock+" unidade(s)":"Esgotado"}</b></div><div class="spec"><small>SKU</small><b>${p.id}</b></div></div><a class="btn btn-green" target="_blank" href="${waLink(`Olá! Tenho interesse no produto ${p.name}. Gostaria de saber mais informações.`)}">Tenho interesse pelo WhatsApp</a></div></div>`}}
});